package loanSystem.entity.enums;

public enum Degree {
    KARDANI,
    KARSHENASI,
    ARSHADPEYVASTE,
    ARSHADNOPEYVASTE,
    HERFEIIDOCTORA,
    PEYVASTEDOCTORA,
    NAPEYVASTEDOCTORA,
    TAKHASOSINAPEYVASTEDOCTORA

}
